# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 11, 24, 9, 39, 41, 572900, tzinfo=utc)),
        ),
    ]
