# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:41
from __future__ import unicode_literals

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20161124_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=chat.models.get_local_time),
        ),
    ]
