# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_customuser_lazy_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname_given',
            field=models.BooleanField(default=False),
        ),
    ]
