# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_guestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='temp_token',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
