# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_guestuser_temp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
