# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20170503_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(to='chat.Room'),
        ),
    ]
