# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20161128_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='connections',
            field=models.IntegerField(default=0),
        ),
    ]
