# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_room_connections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
    ]
