# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20170504_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='private_members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
